# Generated by Django 5.2.15 on 2026-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Nombre de la marca')),
                ('slogan', models.CharField(max_length=300, verbose_name='Eslogan')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#7C3AED', max_length=7, verbose_name='Color secundario')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuraciones del sitio',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('role', models.CharField(max_length=200, verbose_name='Rol/Cargo')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('image', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
