# Generated by Django 5.2.15 on 2026-06-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, max_length=260, verbose_name='Subtitulo')),
                ('image', models.ImageField(blank=True, upload_to='site/banners/', verbose_name='Imagen')),
                ('button_text', models.CharField(blank=True, max_length=80, verbose_name='Texto del boton')),
                ('button_url', models.CharField(blank=True, max_length=220, verbose_name='URL del boton')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Banner del inicio',
                'verbose_name_plural': 'Banners del inicio',
                'ordering': ['-created_at'],
            },
        ),
    ]
