# Generated by Django 5.2.15 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Trabajo o recordatorio')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('due_date', models.DateField(verbose_name='Fecha de entrega')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('done', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Trabajo agendado',
                'verbose_name_plural': 'Trabajos agendados',
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
