# Generated by Django 5.2.15 on 2026-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(max_length=300, verbose_name='Resumen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Imagen')),
                ('category', models.CharField(choices=[('tips', 'Consejos'), ('news', 'Novedades'), ('tutorial', 'Tutorial'), ('inspiration', 'Inspiración'), ('other', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='Estado')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Post del blog',
                'verbose_name_plural': 'Posts del blog',
                'ordering': ['-publication_date'],
            },
        ),
    ]
