# Generated by Django 5.2.15 on 2026-06-25 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('branding', 'Branding'), ('web', 'Diseño Web'), ('social', 'Redes Sociales'), ('print', 'Impresos'), ('video', 'Video'), ('other', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('main_image', models.ImageField(upload_to='portfolio/main/', verbose_name='Imagen principal')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del cliente')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('featured', 'Destacado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Pie de foto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
            },
        ),
    ]
